<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="MainPageSuite" duration-ms="43789" started-at="2018-01-25T14:50:42Z" finished-at="2018-01-25T14:51:26Z">
    <groups>
    </groups>
    <test name="MainPageTest" duration-ms="43789" started-at="2018-01-25T14:50:42Z" finished-at="2018-01-25T14:51:26Z">
      <class name="com.tests.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tests.LoginTest@13fee20c]" name="setUp" is-config="true" duration-ms="21332" started-at="2018-01-25T16:50:42Z" finished-at="2018-01-25T16:51:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="wrongLogin(java.util.Map)[pri:0, instance:com.tests.LoginTest@13fee20c]" name="wrongLogin" duration-ms="2602" started-at="2018-01-25T16:51:03Z" data-provider="CsvDataProvider" finished-at="2018-01-25T16:51:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=1, description=invalid email, password=Aa19141983, email=email Sir_Bobby@i.ua1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tests.LoginTest@13fee20c]" name="tearDown" is-config="true" duration-ms="742" started-at="2018-01-25T16:51:06Z" finished-at="2018-01-25T16:51:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tests.LoginTest@13fee20c]" name="setUp" is-config="true" duration-ms="16515" started-at="2018-01-25T16:51:07Z" finished-at="2018-01-25T16:51:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="wrongLogin(java.util.Map)[pri:0, instance:com.tests.LoginTest@13fee20c]" name="wrongLogin" duration-ms="1689" started-at="2018-01-25T16:51:23Z" data-provider="CsvDataProvider" finished-at="2018-01-25T16:51:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{no=2, description=invalid pass, password=123, email=Sir_Bobby@i.ua}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message is wrong.Expected: email Sir_Bobby@i.ua1 указан неверно!Actual: Пароль указан неверно! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message is wrong.Expected: email Sir_Bobby@i.ua1 указан неверно!Actual: Пароль указан неверно! expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at com.tests.LoginTest.wrongLogin(LoginTest.java:57)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tests.LoginTest@13fee20c]" name="tearDown" is-config="true" duration-ms="526" started-at="2018-01-25T16:51:25Z" finished-at="2018-01-25T16:51:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.LoginTest -->
    </test> <!-- MainPageTest -->
  </suite> <!-- MainPageSuite -->
</testng-results>
